run-name: Trivy Scan
name: Trivy Scan

on:
    push:
        branches: [main, fix/security-Yohaï]

jobs:
    trivy-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Scan dependencies with Trivy
              uses: aquasecurity/trivy-action@0.28.0
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  format: "table"
                  exit-code: "1"
                  ignore-unfixed: false
                  vuln-type: "library"
                  severity: "CRITICAL,HIGH,MEDIUM,LOW"